development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: github_db 
  pool: 5
  username: root
  password: Waterloo123 
  socket: /tmp/mysql.sock 
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: github_db
  pool: 5
  username: root
  password: Waterloo123
  socket: /tmp/mysql.sock
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: github_db
  pool: 5
  username: root
  password: Waterloo123
  socket: /tmp/mysql.sock
